const a = 16;
const b = 8;
const c = 4;
const d = 2;
const e = 1;

console.log(a + b - c * d / e);
console.log(a + b - c / d * e);
console.log(a + b * c - d / e);
console.log(a + b * c / d - e);
console.log(a + b / c - d * e);
console.log(a + b / c * d - e);
console.log(a - b + c * d / e);
console.log(a - b + c / d * e);
console.log(a - b * c + d / e);
console.log(a - b * c / d + e);
console.log(a - b / c + d * e);
console.log(a - b / c * d + e);
console.log(a * b + c - d / e);
console.log(a * b + c / d - e);
console.log(a * b - c + d / e);
console.log(a * b - c / d + e);
console.log(a * b / c + d - e);
console.log(a * b / c - d + e);
console.log(a / b + c - d * e);
console.log(a / b + c * d - e);
console.log(a / b - c + d * e);
console.log(a / b - c * d + e);
console.log(a / b * c + d - e);
console.log(a / b * c - d + e);
